### ISSUE TITLE
CASPR-ROS

### ISSUE THREAD

**Issue by AntonisKats** [darwinlau/CASPR#11]
I have read the paper "CASPR-ROS: A Generalised Cable RobotSoftware in ROS for Hardware". 
I haven't found any github material about it. Is this software available or is it going to be released in the near future? 
Thank you in advance!

**Comment by darwinlau** [comment]
Hi @AntonisKats , sorry for the long delay. We are not currently planning to release CASPR-ROS, but have been upgrading CASPR to be directly compatible with hardware through ROS. If you need more information you are free to directly contact me at darwinlau@cuhk.edu.au
