### ISSUE TITLE
Controlling links that are not cable driven

### ISSUE THREAD

**Issue by Herakles100** [darwinlau/CASPR#12]
Hi, I am currently trying to perform FK/IK on a 3DoF model. Similar to the KNTU planar model available in CASPR. The only difference is that my model has 2 rigid links attached to the cable driven link if the KNTU robot. I was wondering if it was possible to simulate the motor-based actuation of these links without attaching any cables in CASPR. I've attached a figure to make things simpler to understand.

![image](https://user-images.githubusercontent.com/48856045/169662321-2d308f70-2a99-4949-8e76-fb96b2747c5d.png)

**Comment by darwinlau** [comment]
Hi @Herakles100 , sorry for the delayed response. Indeed, it is possible to model partial cable and partial actuated robots (like what you mentioned). In fact, there is an example within CASPR that has that model. Please refer to the robots within ~/data/model_config/models/HCDM. Within there, all robot actually have a hybrid system like in your picture, with the SpiderBot family being identical. 

If you need further help feel free to contact me directly at darwinlau@cuhk.edu.hk
