### ISSUE TITLE
link to CASPR-RViz no longer exists

### ISSUE THREAD

**Issue by aronmeszaros** [darwinlau/CASPR#5]
In CASPRRVizInterface.m the linked repo does not exist, also how could I run my simulation in Rviz? Any hint would be appreciated :)

**Comment by darwinlau** [comment]
Hi, we have enabled the link to the repo now! Please refer to the readme of https://github.com/darwinlau/CASPR and also you can find the CASPR-RViz from https://github.com/darwinlau/CASPR-RViz.
