### ISSUE TITLE
Error loading T7_control.mlx

### ISSUE THREAD

**Issue by pinhaocheng** [darwinlau/CASPR#8]
Hello Professor Lau and team,

I am going through all the tutorials included under scripts/tutorial, however, there was an error when I tried to load T7_control.mlx. I have no problem accessing the others (T1-6 & 8).

Any help provided would be much appreciated!

Pin-Hao

**Comment by darwinlau** [comment]
Hi Pin-Hao,

Thanks for contacting us, would you be able to also let us know what the error is?

Darwin

**Comment by pinhaocheng** [comment]
There's no error code for this actually, MATLAB just pop up and said "Error loading." I have included a snapshot of it below:
![image](https://user-images.githubusercontent.com/20396348/83428863-c628c900-a3f8-11ea-936f-cbb06befbec2.png)

**Comment by darwinlau** [comment]
Thanks Pinhao, I did an update (please pull again) to see if it may be the script being corrupted. Also, I added an "alternative" version that doesn't have any dynamic controls inside. See if it due to that. If there's still problems, let me know what version of MATLAB you are using also.

**Comment by pinhaocheng** [comment]
Thanks for the quick fix! T7 still does not work, but the "alternative" version works now. 

I am using R2018b.

**Comment by darwinlau** [comment]
Hi, so what it could be is that your matlab version does not support the "controls", we have sliders and input boxes etc. So you can use the alternative version for now I guess. Please feel free to contact me at darwinlau@cuhk.edu.hk, it would be great to know more about what you are using CASPR for!
