### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by adhitir** [darwinlau/CASPR#9]
If I want to create a custom cable robot model where the attachment point of the cables are movable (actuated) would it be possible to do so in the simulator?
What I'm asking is if it would be possible to write the IK solver from scratch to add additional actuators.

**Comment by zjy1322733491** [comment]
The creation of mobile cables does not seem to be supported at present

**Comment by darwinlau** [comment]
Hi thanks for the question and interest in using CASPR! 

In fact, the change of cable attachments (mobile cables) is actually supported. To change it, you can use something like:
- model_object.cableModel.cables{1}.attachments{1}.updateAttachmentLocation(r_A, attachment_ref_type) 
To modify the base attachment of cable 1.

We can create an additional cable attachment type (like if it is on a linear rail, or reconfigurable type) to make things easier. 

Please feel free to contact me at darwinlau@cuhk.edu.hk for more support if needed, we can help as we are also working on reconfiguring cable-driven robots also.
